version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo Build phase - no build needed.
  post_build:
    commands:
      - echo Build finished successfully.

artifacts:
  files:
    - '**/*'
